### ISSUE TITLE
Binary classification

### ISSUE THREAD

**Issue by Tranquangdai** [subpic/ava-mlsp#2]
HI, I'm really excited about your implementation.
In predict_mlsp_wide notebook, I've noticed that when you predict image, the score is not the probability but a regression result. I wonder if there is any way to convert it to a binary classification result (which threshold should I use). 

And also, according to the paper, they randomly crop the input image by 224x224, should I do that on every input image?, or to leave as it is?

**Comment by subpic** [comment]
Hi,

The model is trained to predict subjective scores in [1,10]. The convention used in previous works, and when reporting the binary classification results was to threshold at 5. Note that this is not the middle of the score range, which would be 5.5. The reason for this choice is not explained by previous works.

I'm not sure what you mean by the 224x224 crops. Where is this done?
