### ISSUE TITLE
About the implement of the paper

### ISSUE THREAD

**Issue by qingzhouzhen** [subpic/ava-mlsp#6]
HI, @subpic  I read the paper in 3.1 Feature extraction, in the end it said "This is different to when we do fine-tuning of the base network", but the code seems inconsistent with the paper. The code extract feature and save it, then use the extracted feature as input to train the score regression part(e.g. train_mlsp_wide.ipynb), so the basenetwork is not fine-tuninged?

**Comment by subpic** [comment]
The code implements what's mentioned in the paper. The interesting thing about the approach is that there is no need for fine-tuning of the base network; the features extracted directly from the ImageNet pre-trained network are very powerful.
